### ISSUE TITLE
Errror in file : src/epqueue_nif.erl

### ISSUE THREAD

**Issue by egorovd** [silviucpp/epqueue#1]
Hello.
I installed your library and saw a small defect on line 25 :
case code:priv_dir(ezlib)

And taking this opportunity, I want to ask whether there is a queue without priorities, FIFO ?

Thank you.

**Comment by silviucpp** [comment]
Hello,

Thanks for reporting . I've fixed the problem.

Regarding second question epqueue is a priority queue implemented using a binary heap (https://www.hackerearth.com/practice/notes/heaps-and-priority-queues/)

If you search a traditional FIFO you can use:
- https://github.com/fogfish/esq (in case you need a persistent one as well)
- http://erlang.org/doc/man/queue.html (comes with OTP)

Silviu

**Comment by egorovd** [comment]
Thanks for the answer. 
Yes, I'm looking for a traditional FIFO, but with concurrent access, and something I can not find.
